Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -40,8 +40,8 @@ steps:
       pip install checkov
       echo "**********install*******"
       ls
-      checkov -f tf.json -o json >result.json --soft-fail || echo "scan failed"
-      cat result.json
+      checkov -f tf.json -o json >result.json --hard-fail || echo "scan failed"
+      echo "$(cat result.json)"
       echo "*****************"
 # [END Terraform plan scanning]  
 
